# ##########################################################
# This file is used by modules using MBIMGUI to locate MBIMGUI
# and its dependencies
# ##########################################################
include(GNUInstallDirs)

# Global variables
set(MBIMGUI_DIR ${CMAKE_INSTALL_PREFIX}/../MBIMGUI/${CMAKE_INSTALL_INCLUDEDIR})
set(MBIMGUI_LIB_DIR ${CMAKE_INSTALL_PREFIX}/../MBIMGUI/${CMAKE_INSTALL_LIBDIR})
set(SUB_MOD_DIR ${MBIMGUI_DIR}/imgui)

set(IMGUI_DIR ${SUB_MOD_DIR}/Imgui/)
set(IMGUIBROWSER_DIR ${SUB_MOD_DIR}/imgui-filebrowser/)
set(IMPLOT_DIR ${SUB_MOD_DIR}/implot/)
set(IMEMEDIT_DIR ${SUB_MOD_DIR}/imgui_club/imgui_memory_editor)
set(IMSPINNER_DIR ${SUB_MOD_DIR}/imspinner/)
set(IMTOGGLE_DIR ${SUB_MOD_DIR}/imgui_toggle)

set(MBIMGUI_LIB_RELEASE_DIR ${MBIMGUI_LIB_DIR}/Release/)
set(MBIMGUI_LIB_DEBUG_DIR ${MBIMGUI_LIB_DIR}/Debug/)

message("${config_suffix}")

# import lib
add_library(MBIMGUI STATIC IMPORTED)

# Set link and includes path
find_library(MBIMGUI_LIBRARY_PATH_RELEASE MBIMGUI HINTS ${MBIMGUI_LIB_RELEASE_DIR})
find_library(MBIMGUI_LIBRARY_PATH_DEBUG MBIMGUI HINTS ${MBIMGUI_LIB_DEBUG_DIR})

set_target_properties(MBIMGUI PROPERTIES
    IMPORTED_LOCATION_RELEASE ${MBIMGUI_LIBRARY_PATH_RELEASE}
    IMPORTED_LOCATION_DEBUG ${MBIMGUI_LIBRARY_PATH_DEBUG}
    IMPORTED_LOCATION_RELWITHDEBINFO ${MBIMGUI_LIBRARY_PATH_DEBUG}
    IMPORTED_LOCATION_MINSIZEREL ${MBIMGUI_LIBRARY_PATH_RELEASE})

set_target_properties(MBIMGUI PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${MBIMGUI_DIR};${IMGUI_DIR};${IMPLOT_DIR};${IMGUIBROWSER_DIR};${IMEMEDIT_DIR};${IMSPINNER_DIR};${IMTOGGLE_DIR}")

message("${MBIMGUI_LIBRARY_PATH}")